### ISSUE TITLE
Install guide?

### ISSUE THREAD

**Issue by jmacul2** [KeithDHedger/CastReceiver#1]
I love the idea of this project using omxplayer instead of the broken gstreamer as a upnp renderer.  Any install guide you can point me to?  I seem to be running into a bunch of compile error/issues.

Thanks!

**Comment by KeithDHedger** [comment]
just the usual configure/make/make install.
what errors are you getting?

**Comment by jmacul2** [comment]
libupnp is requiring large file support

`/usr/include/upnp/FileInfo.h:22:2: error: #error libupnp uses large file support, so users must do that, too
 #error libupnp uses large file support, so users must do that, too
 `

Do I need to build libupnp from source?

**Comment by KeithDHedger** [comment]
probably yes this was built on an LFS system where everything is compiled from source what distro and version are using I may be able to help more if know a bit more about your system

**Comment by jmacul2** [comment]
RB3+ on Rasbian Buster

**Comment by KeithDHedger** [comment]
Sorry don't know what 'buster' is what is the version number?
Just looked at the build scripts and yes you need to compile libupnp with large file support like so:
LFSFLAGS="${LFSFLAGS} -D_LARGE_FILE_SOURCE -D_FILE_OFFSET_BITS=64"
CFLAGS="$LFSFLAGS" CXXFLAGS="$LFSFLAGS" ./configure
make sudo make install
You may want to install in /usr/local/* ( which should be the default for configure ), that way you can have both versions of the  lipupnp library's installed side by side.
Alternativly get on to the packager of libupnp and ask for the large file version to be packaged, don't know why they didn't do that anyway.

Let me know how you get on, closing for now.
